"""Add Token models

Revision ID: 6df22e09f833
Revises: c5a415db630b
Create Date: 2025-12-15 19:15:57.840599

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6df22e09f833"
down_revision = "c5a415db630b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text_id", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["text_blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["text_id"],
            ["texts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("token_blocks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_token_blocks_block_id"), ["block_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_token_blocks_text_id"), ["text_id"], unique=False
        )

    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("form", sa.String(), nullable=False),
        sa.Column("base", sa.String(), nullable=False),
        sa.Column("parse", sa.String(), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["text_blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tokens_block_id"), ["block_id"], unique=False
        )

    op.create_table(
        "token_revisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("token_block_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_block_id"],
            ["token_blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("token_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_token_revisions_author_id"), ["author_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_token_revisions_token_block_id"),
            ["token_block_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_revisions_token_block_id"))
        batch_op.drop_index(batch_op.f("ix_token_revisions_author_id"))

    op.drop_table("token_revisions")
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tokens_block_id"))

    op.drop_table("tokens")
    with op.batch_alter_table("token_blocks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_blocks_text_id"))
        batch_op.drop_index(batch_op.f("ix_token_blocks_block_id"))

    op.drop_table("token_blocks")
    # ### end Alembic commands ###
