"""Add Author

Revision ID: 8951ab61803e
Revises: 1f0affa10b64
Create Date: 2025-12-09 20:31:30.170330

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8951ab61803e"
down_revision = "1f0affa10b64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("texts", sa.Column("author_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_text_author_id"), "texts", ["author_id"], unique=False)
    with op.batch_alter_table("texts") as batch_op:
        batch_op.create_foreign_key(
            "fk_texts_author_id", "texts", ["author_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("texts") as batch_op:
        batch_op.drop_constraint("fk_texts_author_id", type_="foreignkey")
    op.drop_column("texts", "author_id")
    # ### end Alembic commands ###
