"""Add Text.language

Revision ID: c3f44524bcf9
Revises: 0d14c5b4b080
Create Date: 2025-12-14 12:48:13.351096

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c3f44524bcf9"
down_revision = "0d14c5b4b080"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("texts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language", sa.String(), nullable=True))

    op.execute("UPDATE texts SET language = 'sa' WHERE language IS NULL")

    with op.batch_alter_table("texts", schema=None) as batch_op:
        batch_op.alter_column("language", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("texts", schema=None) as batch_op:
        batch_op.drop_column("language")

    # ### end Alembic commands ###
