"""Add Text.updated_at

Revision ID: c5a415db630b
Revises: c3f44524bcf9
Create Date: 2025-12-14 22:01:43.603331

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c5a415db630b"
down_revision = "c3f44524bcf9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("texts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))

    op.execute("""
        UPDATE texts
        SET updated_at = COALESCE(created_at, published_at, datetime('now'))
    """)

    with op.batch_alter_table("texts", schema=None) as batch_op:
        batch_op.alter_column("updated_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("texts", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
    # ### end Alembic commands ###
